# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r:
  - release

r_github_packages:
  - r-lib/covr

r_packages:
  - libgsl0-dev

after_success:
  - Rscript -e 'covr::codecov()'
