# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - sudo apt-get install libgsl0-dev

r:
  - release

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
