# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false # tex on travis R-dev produces lots of warnings

before_install:
#  - sudo apt-get install libgsl0-dev libgsl2
  - sudo apt-get update
  - sudo apt install libgsl-dev

# env:
#  global:
#    - ALLOWED_WARNINGS = 3 
#    - ALLOWED_NOTES = 3

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - r-lib/covr
  - cran/gsl


after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
  - master
