# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - sudo apt-get install libgsl0-dev

# new
addons:
  apt:
    packages:
      - libgsl-dev
install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install(dependencies = TRUE, upgrade_dependencies = TRUE)'
# end new

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - r-lib/covr
  - cran/gsl


after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
  - master
